// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYCiKVsMe40hhfTZ8XgaWNkM_o_dJ-n-Q',
    appId: '1:727798431223:web:72ef30a7f0e2af0ad582f2',
    messagingSenderId: '727798431223',
    projectId: 'warren-98d49',
    authDomain: 'warren-98d49.firebaseapp.com',
    storageBucket: 'warren-98d49.firebasestorage.app',
    measurementId: 'G-06TXPPMDHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq0cVh71gnrNzUf7EL4n_2BWd3pQVd6Uw',
    appId: '1:727798431223:android:660e9216773b5a09d582f2',
    messagingSenderId: '727798431223',
    projectId: 'warren-98d49',
    storageBucket: 'warren-98d49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmHzgjzf-sszrN1uolvbPdvo9ddcS5rVk',
    appId: '1:727798431223:ios:47748571cbce0d32d582f2',
    messagingSenderId: '727798431223',
    projectId: 'warren-98d49',
    storageBucket: 'warren-98d49.firebasestorage.app',
    iosBundleId: 'com.example.warren',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmHzgjzf-sszrN1uolvbPdvo9ddcS5rVk',
    appId: '1:727798431223:ios:47748571cbce0d32d582f2',
    messagingSenderId: '727798431223',
    projectId: 'warren-98d49',
    storageBucket: 'warren-98d49.firebasestorage.app',
    iosBundleId: 'com.example.warren',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYCiKVsMe40hhfTZ8XgaWNkM_o_dJ-n-Q',
    appId: '1:727798431223:web:7feb832d7f9246f1d582f2',
    messagingSenderId: '727798431223',
    projectId: 'warren-98d49',
    authDomain: 'warren-98d49.firebaseapp.com',
    storageBucket: 'warren-98d49.firebasestorage.app',
    measurementId: 'G-JGSBWS7G11',
  );
}
